name: Cryptol typecheck
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cryptol Version
      run: cryptol --version

    - name: Check Cryptol Files
      run: bash scripts/load_all_cry_files.sh
