name: Cryptol
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 10 * * *" # 10am UTC -> 2/3am PST
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    steps:
    - name: Installing dependencies..
      run: |
        # Sync repos
        apt update
        # Install git
        apt install -y git
        if ! apt list --installed 2>/dev/null | grep -q "git.*"; then
          apt install -y git
        elif apt list --installed 2>/dev/null | grep -q "git.*"; then
          true
        else
          exit 255
        fi
    - name: Checkout
      uses: actions/checkout@v2
    - name: What cryptol version is installed?
      run: cryptol --version
    - name: Check Cryptol Files
      run: bash scripts/load_all_cry_files.sh
