name: Cryptol
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 10 * * *" # 10am UTC -> 2/3am PST
  workflow_dispatch:

jobs:
  load:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    steps:
    - name: Installing dependencies..
      run: |
        apt update
        apt install -y git
    - name: Checkout
      uses: actions/checkout@v4
    - name: Cryptol Version
      run: cryptol --version
    - name: Check Cryptol Files
      run: bash scripts/load_all_cry_files.sh

  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    needs: load
    steps:
    - name: Installing dependencies..
      run: |
        apt update
        apt install -y git
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check Cryptol Properties
      run: bash scripts/test_all_properties.sh

  prove:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/galoisinc/cryptol:nightly
      options: --user root
    needs: check
    steps:
    - name: Installing dependencies..
      run: |
        apt update
        apt install -y git
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prove Cryptol Properties
      run: bash scripts/prove_all_properties.sh
    - name: Upload Proof Artifacts..
      uses: actions/upload-artifact@v4
      with:
        name: prove-artifact
        path: |
          manual_proves.txt
          fast_proves.txt
