name: Lint

on: [push, pull_request]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker:latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check whitespace
        run: |
          test -f .editorconfig
          ec
